### ISSUE TITLE
How do I get an external address attached to the ingress controller

### ISSUE THREAD

**Issue by derryx** [xetys/hetzner-kube#103]
Hi!

I am quite new to Kubernetes and I might ask a stupid question. So please forgive me.

I am able to create a cluster and deploying helm charts in that cluster works fine. But when I install an ingress controller (I want to install Jenkins-X) I always end up with the external address in state "pending". What do I need to do to get an external address attached? Jenkins-X does not proceed with its installation as long there is no external address.

Thanks
Thomas

**Comment by xetys** [comment]
There are two ways of exposing services, LoadBalancer service type, and ingress. You are asking for LoadBalancer services. This means, a cloud provider takes a floating IP from the cloud infrastructures and connects to your cluster. This is a feature, which most commonly exists only in cloud kubernetes clusters, like on GCP, AWS or Azure. There also a custom one inside rancher. \

For the rest you use ingress. The ingress means, you declare an additional resource called `Ingress` which takes a service and a host name and makes the binding. You need a ingress controller to do this in real. For this purpose, you might use nginx ingress controller. You have one in the hetzner-kube admin section.

A quick google lead me to an obvious issue you ran into: as of http://jenkins-x.io/commands/jx_install/ jenkins-x automatically installs an nginx ingress controller for you. But the default ingress controller tries to get its IP over an external IP from a load balancer. That is not the way we do this in custom clusters like hetzner-kube. Here the ingress controller must be deployed as DaemonSets, running on every (specified) node with hostNetwork on. In order to use jx with a hetzner-kube cluster, you must use `--skip-ingress` and install `hetzner-kube cluster addon install ingress -n your-cluster` in advance.

I didn't test this, but this should work. Please close this issue if your issue is resolved.

**Comment by xetys** [comment]
yeah, really looks like a JX issue here.

**Comment by derryx** [comment]
This seems to be an Jenkins X problem. Closing issue.
