### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by pierreozoux** [xetys/hetzner-kube#12]
Hello! Looks cool :) thanks for sharing!

I'm working on https://github.com/indiehosters/libre.sh/issues/161

And I have various questions :
 - why not Tectonic? (No ipxe support, right?)
 - is it HA? ( Searching quickly from mobile, didn't find)
 - how to configure flannel or weave with encryption? (Public cloud so, would be better :) )
 - do you prefer weave or flannel?
 - is it based on kubeadm?
 - just curious, why openEBS and not rook?

And you probably are also looking for the sweets pot right? I think it would be cool to provision masters on VMs and workers on there cheap hardware.

I'll look more on the code once I'm on desktop, but thanks a lot for sharing!

**Comment by xetys** [comment]
> why not Tectonic? (No ipxe support, right?)

Because tectonic is not a free product. It sure has a free plan, but even this needs a license. This would lock users into this distinct product. And the PXE stuff currently just doesn't work, as hcloud has no VLAN support right now.

> is it HA?

Not yet, but planned to be implemented soonly.

> how to configure flannel or weave with encryption? (Public cloud so, would be better :) )

I think this should be done over etcd like kismatic is doing that. But yeah, it's a point. Feel free to open issues and contribute PRs ;)

> do you prefer weave or flannel?
currently, flannel, as it integrates with the hcloud-controller-manager. Out of that scope, there is no preference. But the focus is on open products over free products with paid plan to prevent lock-ins.

> is it based on kubeadm?
yes. As an official tool from kubernetes itself, I expect it to overperform its maturity over other tools over time.

> just curious, why openEBS and not rook?

That was an example in my blog article. The tool itself does not integrate with one of the tools.

About the cheap hardware point. As you know its kubeadm. you can add any new nodes just by logging into your master and `kubeadm token create --print-join-command` and use that command for new nodes, wherever they are.

Please state if you have more questions or close the issue :)

**Comment by pierreozoux** [comment]
Thanks a lot for the detailed insight!

We'll know soon about tectonic ;)

https://github.com/coreos/tectonic-forum/issues/276
