### ISSUE TITLE
Reference design

### ISSUE THREAD

**Issue by pierreozoux** [xetys/hetzner-kube#17]
About the use of hardware, I plan on writing some documentations for that.
The idea would be to pick 3 nodes in Hetzner offer, and do a Reference Implementation using:
 - 3 HA masters (in hetzner cloud)
 - encrypted networking
 - 3 baremetal workers
 - rook
 - ingress with tls and le support

This would be documentation at first, but on the way to do that, I'll be able to identify potential candidates for automation.

I'll ask hetzner if they are kind enough to borrow some servers.
I don't care much about cpu/ram, but I'd like something like:
 - 1 SSD for system
 - 2 HDD for storage
(It should cover most of people's need)

I know little about go, but this project is the opportunity to learn :)
And if you looked at http://libre.sh you know I'm serious about this!

 - [x] contact hetzner to ask for 2 epyc servers

**Comment by xetys** [comment]
Feel free to do that and to share your experience. 

I already built a reference setup (full on Hetzner cloud, as the name "reference" states) with:

* wireguard network encryption
* 3 etcd + master nodes (the "simpler" version)
* rook as reference workload storage
* some stupid pods to proof the cluster worked when I started to DDoS my primary master

I had no ingress running, as this is an easy step and with kube-lego actually doing all you mentioned.

Rook started to work a bit slow after the master was partially down, but at least did its job.

For those "features" I already mentioned, I see an addon command. I would also offer alternatives like traefik or OpenEBS. The point is, I want hetzner-kube to be a universal tool, rather than a playback of the cluster "how I'm using it". So my focus on the reference system is:

* best practice of setting up the components the official way
* not bringing in to much specific complexity
* the good design demands compromise stuff ;)

Giving an example:

You want to do network encryption. This can be achieved using WireGuard, so you setup k8s like in a private network, which spans over a public internet using up-to-date crypto standards. 

Do all future users also want this? Should it be an "optional" feature? HA clustering does also work with public IPs. The fact is, bringing a "default" option is the most simple way for the developer, and a feature-toggle the most desired thing for UX. This is some material for discussion

**Comment by pierreozoux** [comment]
Yes, totally understand your point of view.

thanks a lot for your hard work, I'll do my part!

**Comment by xetys** [comment]
Hey,

as of #42 and addon support, it's possible to build your reference design in pure hetzner-cloud. With #37 and pending #40 you will be able to add any other server, say a hetzner dedicated server to the cluster. So I think I can close this.

**Comment by pierreozoux** [comment]
Ok, I just managed to delete a worker node and recover the cluster \o/
It was with downtime, but still happy!

For reference, you need to change this line to 2 :)
https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/rook-storageclass.yaml#L8

**Comment by xetys** [comment]
could you explain more detailed, what you mean by recover the cluster? What happened after removing the node and what did you do to recover it?

**Comment by pierreozoux** [comment]
Once you delete one worker node (I had 3), it is unhealthy, and the pods will not manage to remount the volume.
I thought it would, but it doesn't, I need to investigate more, and maybe open an issue with rook.

Then, when I re-add a node, it get healthier, but still no luck. I realized there was one more OSD that rook/ceph created, I deleted it, and after some minutes, it recovered.

But yeah, it doesn't self-heal :)

Actually thinking about it, I'll try with 4 worker nodes. Because If I want 3 mon, 1 on each worker, with 2 nodes, we'll have just 2 mon, and no leader. I'll make a video with this experiment and share experience here.

BTW, I got the 2 EPYC servers from Hetzner \o/ still waiting the HW, but I'm excited!

**Comment by xetys** [comment]
wow, that's cool!

**Comment by lakano** [comment]
@pierreozoux Thanks for your experiments, I'm following your tests reports :)

**Comment by xetys** [comment]
as of the current version, the "setup kubernetes" logic is not hardly coupled to the hetzner cloud API. It only depends on a set of servers, which are reachable over SSH.
In so far it is theoretically possible to use hetzner-kube on any server you like. Practically there is no way how to tell the CLI to do that. 

The right way would be to provide a config file with all servers listed. 

Is that in the scope of hetnzer-kube? That's fairly a good question, as on the one hand, it's not, as this project is dedicated to hetzner. On the other it is, as it technically is able to. That's a topic to discuss

**Comment by xetys** [comment]
The preconditions for the servers? They should exist, with ubuntu 16.04 and SSH access. That's it.

The preconditions for hetzner-kube? The CLI itself is checking the API in order to decide if it should create new servers or not. If it asks the API and the servers do exist, then it just do the actual installation. This doesn't depend on hetzner anymore. So the precondition would look like:

```
$ hetzner-kube cluster create --provider none --config-file my-servers-with-ips.yaml 
```

So the tool checks if these servers exist and meet the requirements (which already happens when you add an external worker) and if so, run the normal routine.

That's how it would be possible to solve

**Comment by adrianog** [comment]
But there is no private networking setup between the servers so that is also something that I must add to the preconditions? Surely I don't want to talk on the public IP without wireguard / some form of VPN?

**Comment by loxy** [comment]
Maybe Rancher is something for you: 
http://rancher.com
https://github.com/rancher/rancher

**Comment by adrianog** [comment]
Thank loxy, but that all seems to be Hetzner Cloud specific, and I have dedicated bare metal servers. The cost muliplier on Hetzner Cloud as opposed to bare metal seems to be in the region of 5X/10X .

I am very happy with my dedis, just want a way to deploy k8s, openshift on it.

Looks like the best route is manually setup wireguard on the public IP, and then use Openshift ansible playbooks / [Let's kube scripts](https://goo.gl/NHyM5k) , [kubeadm](https://goo.gl/LXTLy4), or any other ansible-based installation.

I was hoping this project could help with regard to the Wireguard part, not sure if I can extract that part / take inspiration from it, otherwise I'll just try and do it manually.

**Comment by loxy** [comment]
With Rancher you can easily install on bare metal AND on cloud providers side by side to construct a cluster. It is much like hetzner-kube for all kind of servers, clouds, vm etc. I thought you are interested in hetzner, thats why I posted the links. You should have a look...

hetzner-kube is more specific, but also a great tool. But I think out of scope for your kind of requirements

**Comment by xetys** [comment]
so you are looking for a wireguard solution? I did a side project called wgctl (https://github.com/xetys/wgctl) which actually uses hetzner-kube internals do just setup wireguard on any server you want. 

As @loxy said, you can use rancher 2 for your setup. I have bad experience with rancher until 1.6.x, but 2 is doing almost good. I compared how RKE is doing stuff when it comes to HA and stuff, and it is very much like hetzner-kube or kube-spray (another possibly interesting project for you. It's ansible)

**Comment by adrianog** [comment]
Thanks xetys, I'm having a look at the source code for hetzner-kube  and it looks good - you're right it's just a matter of separating node provision (skip this from the cloud, use list passed in) from node setup (wireguard etc, this I will use thank you :-)), and the kubernetes setup (will use this as well, or might plug in some ansible stuff if I want to stop at the wireguarding).

I'll take a look at wgctl too, might be all I need.

**Comment by adrianog** [comment]
Just to add on to my own comments in case someone finds it useful: Hetzner [DOES seem to support private networking with a vSwitch on your dedis](https://wiki.hetzner.de/index.php/Vswitch/en). I was misled by an [old twitter comment](https://twitter.com/hetzner_online/status/955781300513857536?lang=en) that I think only applies to Hetzner Cloud.

That changes the game - I still like rancher after I've read about it because of the heterogeneity of the potential setup (i.e. add nodes somewhere else, anywhere, later), but I will go with the private network setup for now, and probably try Openshift OKD directly on it.

Many thanks for all the info.
