### ISSUE TITLE
OpenEBS or Hetzner-CSI?

### ISSUE THREAD

**Issue by mysticaltech** [xetys/hetzner-kube#281]
A question I have, in the article linked, you use OpenEBS, is it still useful if we use Hetzner CSI driver? Or are both compatible and working together? My ultimate goal is to install TiBD, a cloud native MySQL replacement. Thanks in advance!

**Comment by dsteinberg111** [comment]
Hi,
I tested the Hetzner-CSI. You can Use them both but the hetzner-csi will set "storageclass.kubernetes.io/is-default-class: 
true" - so if you create a default Persistent Volume it will alway be hetzner-csi - but that is not the Problem.

The main problem is that hetzner-csi is bound to the datacenter. So this PVC cannot be mounted by Nodes outside of the Datacenter. Also It seems to me that it cannot reliable unbound from Node so that even when the node is in the same Datacenter it may not work.

This resulted in a lot of PVCs that could not be accessed, PODs got stuck and it was a lot of handwork to get it Up again.

Finally I reworked all to use "openebs-jiva-default" Storageclass. 

Currently I m looking at that rook.io because I need a "readwriteMany" PVC (A Webroot where multiple PODs need access to) and openebs does not support multiple pods using the same PVC.

**Comment by gentios** [comment]
@dsteinberg111 why did u choose **openebs-jiva** vs **openebs-cstor**. I am not quite familiar with OpenEBS but they recommend the **openebs-cstor** engine.

**Comment by dsteinberg111** [comment]
That was due to an mistake from me. I did not update the helm repo prior so I had openebs 0.9 and was wondering myself... but all worked. Now I updated the helm chart and the api- service from openebs is not working anymore. I got errors like: failed to apply resources: [CustomResourceDefinition.apiextensions.k8s.io "cstorpoolclusters.openebs.io" is invalid: spec.scope: Invalid value: "Cluster": field is immutable

But It seems I m the only one with that error.

I also want to change to cstore and implement that nfs - Store from https://docs.openebs.io/docs/next/rwm.html

**Comment by gentios** [comment]
@dsteinberg111 I had also some problems with openebs, that's why I was thinking more to go with hetzner-csi.

 But since hetzner-kube deploys in more than 1 datacenter that would be a problem if the volumes wouldn't be accessible from nodes of other datacenters

**Comment by koehn** [comment]
> @dsteinberg111 I had also some problems with openebs, that's why I was thinking more to go with hetzner-csi.
> 
> But since hetzner-kube deploys in more than 1 datacenter that would be a problem if the volumes wouldn't be accessible from nodes of other datacenters

You can specify the datacenter(s) to use with the `--datacenters` option.

**Comment by tholu** [comment]
What are you guys currently using? I'm right now thinking about what storage option to choose as a best-practice.

**Comment by koehn** [comment]
I went with all my nodes in a single datacenter, and use the hetzner CSI module for PVC. I have a relatively simple cluster (5 x 8GB/2CPU) with a few dozen pods. I use velero/restic for backups in Wasabi, retaining them for ninety days (since Wasabi charges you for ninety days of storage, and at $0.0059USD/GB, it's pretty cheap anyway). 

As much as possible I put storage like Nextcloud into Wasabi for infinite scale.

**Comment by drallgood** [comment]
I'm at the same point.. not super happy with hcloud-csi as storage gets stuck when a node isn't reachable and because of that I constantly have to deal with unavailable pods (as pods can't be rescheduled to other nodes).
I've already moved everything I can to backblaze b2 (another S3 storage provider)

How are you guys using openEBS? Cstor or Jiva? How does that work in practice on your Hetzner nodes?  
Would be great if someone cloud provide an overview of their setup

**Comment by cristianrat** [comment]
@drallgood Got anything good running?
the hetzner csi is subpar as far as I am concerned

**Comment by drallgood** [comment]
@cristianrat Not really. Gave up on K8S for my personal stuff a long time ago 😂
As much fun as it was, it was just total overkill

**Comment by cristianrat** [comment]
fair enough :)

**Comment by mysticaltech** [comment]
Hey folks, since creating that issue a long time ago, we built https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner with support for both Hetzner CSI and Longhorn. The latter has more options, and we can use either node storage or volumes, which is very practical and it also has a great UI via Rancher.
