### ISSUE TITLE
[question] SSL certs management and DNS configuration

### ISSUE THREAD

**Issue by lakano** [xetys/hetzner-kube#68]
Hi,
Thanks again for this amazing project, just created a new cluster in few minutes, it's magic!
I installed addons helm, rook, ingress and cert-manager, but I don't really known how to deal with SSL certs.

1) What I need to do to issue a new cert please? 
2) I've created a HA cluster ( 3 master, etcd included, kubernetes control self-hosted ). Which master IP address I need to use in my registrar DNS configuration please?

Thanks!

**Comment by xetys** [comment]
Hey, thanks for the feedback.

About 1. Please take a look at the conversation in #45. There are links to resources, which describe how to either use the kube-lego style or the new way by using crd.

About 2., At the moment you should use the IP of the first master. That's because the other IPS are not setup for the other master nodes. If they would be added there, you could easily balance over these.

**Comment by lakano** [comment]
I put the links here for the record (not yet tested) : 
https://github.com/jetstack/cert-manager/tree/master/docs/api-types/issuer
https://github.com/jetstack/cert-manager/blob/master/docs/user-guides/ingress-shim.md
