### ISSUE TITLE
Don't replace kubeconfig when doing "hetzner-kube cluster kubeconfig"

### ISSUE THREAD

**Issue by KrustyHack** [xetys/hetzner-kube#71]
Ay,

I did the command `hetzner-kube cluster kubeconfig --name demo` and my ~/.kube/config was totally replaced with the hetzner kube cluster. All my other clusters config were erased.

I'm using version "0.2.1".

**Comment by pierreozoux** [comment]
Looking at the code, it must have been backed up. Can you check if it is backed up?

But still agree that the UX should be a bit more polite ;)

**Comment by xetys** [comment]
Hey. Use the `--print` or `-p` flag to print the kubeconfig rather than install it (`hetzner-kube cluster kubeconfig -n mycluster -p`). Then you just can do `kubectl --kubeconfig=./cluster.conf`.

For my own clusters I'm using my tool https://github.com/xetys/kubeconfig-loader which does very easy rotation of kubeconfigs.

What I would suggest is to add an "do you want to override the existing config?" question if there is one

**Comment by xetys** [comment]
had missed to ad the `> cluster.conf` in my recent comment
