### ISSUE TITLE
Support extra kubeadm init parameters

### ISSUE THREAD

**Issue by lakano** [xetys/hetzner-kube#81]
Hi !
Is it possible to permit to support extra parameters when installing the cluster please?
For example, we would like to use CoreDNS ( will be the default in k8s v1.11 ) and we can use it manually by default since k8s 1.9 like this:
kubeadm init --feature-gates=CoreDNS=true

I suppose it's not the only case where this could be useful to give extra parameters to kubeadm.
Thanks!

**Comment by xetys** [comment]
I'm not sure if we should enable this in a totally free way, like giving the option to pass all arguments. The reason here is the intention of hetzner-kube beeing a hetznercloud specific tool, which installs k8s as we know it runs well on it. Adding this level of freedom will cause a lot of new issues. I would prefer to add specific features over a flag, configuring it properly in the tool, rather than the other way.

**Comment by lakano** [comment]
Ok I understood. So I close this issue and I'll do a manual upgrade to apply CoreDNS.

**Comment by xetys** [comment]
possibly a case for `hetzner-kube cluster create <...> --core-dns`?

**Comment by xetys** [comment]
or ship coredns as an add-on

**Comment by lakano** [comment]
I don't known if it's useful, because we can manually upgrade to CoreDNS, and this will be shipped in next k8s release.
